jira:
  username: goncalo.valverde@gmail.com
  password: FBHZdShdtabEvifknfqc32A0
  url: https://varanda.atlassian.net
  customfield:
    storypoints: customfield_10043
output:
        filename: "nominations_bug_data.xlsx"
jql_query: PROJECT ='FUBAR'
            AND
            issuetype="story"