# Where should we put our cache files?
# Remember that the temporary directory goes away after a reboot
cache_dir: /tmp

# Where are we storing the input configurations?
config_dir: conf

# Run in debug mode?
debug: False

# What will be the webroot ?
# This is to allow reverse proxy. Not yet implemented
web:
  root: /
