version: 1
formatters:
  simple:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(funcName)s - %(message)s'
  extended:
    format: "%(asctime)s %(name)s %(levelname)s: %(message)s"

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout
  file_handler:
    class: logging.FileHandler
    level: DEBUG
    filename: /tmp/seshat.log
    formatter: simple

loggers:
  dev:
    level: DEBUG
    handlers: [console, file_handler]
    propagate: no

  test:
    level: DEBUG
    handlers: [file_handler]
    propagate: no

  prod:
    level: INFO
    handlers: [file_handler]
    propagate: no

root:
  level: DEBUG
  handlers: [console,file_handler]